### ISSUE TITLE
Bold characters at certain font sizes are higher than non-bold

### ISSUE THREAD

**Issue by dlockhart** [BrightspaceUI/typography#112]
This is an issue with the version of Lato that we're using, and only occurs at certain font sizes. That leads me to believe that it's a rounding issue.

![broken fonts](https://user-images.githubusercontent.com/5491151/41418643-20519a90-6fbe-11e8-9f71-dfe19fdaa376.png)

Note in the above screenshot how the "16px" version the middle "x" which is bolded is `1px` higher than the non-bold text.

Upgrading to a newer version of the Lato font may resolve this issue, but we should ensure that it still contains all the glyphs required for localization.

**Comment by mpharoah-d2l** [comment]
Bolded 16px Lato text seems to be rendered pretty poorly in Firefox on Windows, with parts of letters being more bold than others. However, it renders fine on Firefox in Linux, and also in Chrome (which I think uses its own font rendering engine independent of the OS).

**Comment by dlockhart** [comment]
Repo is archived.
