### ISSUE TITLE
Uppercase letters don't line up if first character

### ISSUE THREAD

**Issue by awikkerink** [BrightspaceUI/typography#79]
A, G, H, S, T, V, W, X, Y, Z line up differently than the other characters. If one of other characters are used in a heading, the columns don't line up.

![kl85-awikkerin-44444-d2l-le-6609-discussions-list-ou 6609](https://cloud.githubusercontent.com/assets/7862298/21322722/58c5a65e-c5e8-11e6-9348-70a1181e983b.png)
![localhost-8080-components-d2l-typography-demo-](https://cloud.githubusercontent.com/assets/7862298/21322752/7cbb401e-c5e8-11e6-833f-6d66dc381665.png)

**Comment by dlockhart** [comment]
Repo is archived, feel free to open in lit-core if this is still an issue.
